[package]
name = "typing-proof-host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
hex = "0.4.3"
risc0-zkvm = "3.0.4"
sha2 = "0.10.8"
typing-proof-methods = { path = "../methods" }
